export { sendEmail } from "./sender";
export {
  sendWelcomeEmail,
  sendInviteEmail,
  sendNewLeadEmail,
  sendTaskReminderEmail,
  sendTaskOverdueEmail,
  sendDailyDigestEmail,
  sendStageChangeEmail,
  sendPasswordResetEmail,
  sendTrialExpiryEmail,
  sendWeeklyReportEmail,
  getWelcomeEmailHtml,
  getInviteEmailHtml,
  getNewLeadEmailHtml,
  getTaskReminderEmailHtml,
  getTaskOverdueEmailHtml,
  getDailyDigestEmailHtml,
  getStageChangeEmailHtml,
  getPasswordResetEmailHtml,
  getTrialExpiryEmailHtml,
  getWeeklyReportEmailHtml,
} from "./templates";
